### ISSUE TITLE
Update to latest wemake-python-styleguide

### ISSUE THREAD

**Issue by strmwalker** [pawamoy/wps-light#196]
Hi! Can you update please wemake-python-styleguide to latest version, which is 0.17.0 https://github.com/wemake-services/wemake-python-styleguide/releases/tag/0.17.0 ?

**Comment by pawamoy** [comment]
Hi! Unfortunately, as stated in the readme, I don't maintain this project anymore. I've stopped using wemake-python-styleguide and flake8 entirely.

If you'd like to take over maintenance, I can transfer owership of the repository to you, or add you as a collaborator, and give you push access on pypi.org :slightly_smiling_face: WDYT?
